# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff22d28337b632141b6ff022b40fd14df9b88f8c48dac4e13862692c56463795cf4fc1c78bef23e4ac3615b0851229d3ad53a291838ae4f3011e9fd0472e6d0f

test:
  secret_key_base: 45e7cda745f51c5f5af47b0f423773c5349aeb70e9268e8c093337211084af2e409184652851819317b6ac07578ae1459483595e9a61a10d79dd3fb7391b8721

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
